language: python
python:
    - "3.6"

install:
    pip install -r requirements.txt

script:
    - pytest -s --cov=nba_scraper test_unit.py
env:
  - MOZ_HEADLESS=1

after_success:
    - codecov

addons:
  firefox: latest
